# Site settings
title: Marcela e Raphael
email: raphaelfmf@gmail.com.com
description: "Casamento Marcela e Raphael"
url: "http://www.marcelaeraphael.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
